### PR TITLE
Changes for v0.13.0 release

### PR DESCRIPTION
**Pull request by jmsktm**
## Change description

> Description here

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

### CODE REVIEW

**Comment by foxish** [comment]
Can you cherrypick the commits in https://github.com/signadot/charts/pull/50 into this PR?

**Comment by jmsktm** [comment]
> Can you cherrypick the commits in https://github.com/signadot/charts/pull/50 into this PR? That way - the readme will be part of the helm tar.gz that gets built when this merges.

Should we rather merge that, and then add these changes on top of that?

**Review by foxish — APPROVED** [review]
LGTM

**Comment by jmsktm** [comment]
Merged the doc PR and released this branch.

**Pull request merged**
