### PR TITLE
Update of values and params documentation for operator v0.13.0

### PR DESCRIPTION
**Pull request by daniel-de-vera**
## Change description

Update of default values and params documentation for the operator release v0.13.0.

### CODE REVIEW

**Review by foxish — APPROVED** [review]
LGTM

**Comment by jmsktm** [comment]
The build for this PR failed in the `Run chart-releaser` step. Is it ok to ignore that and proceed with merging https://github.com/signadot/charts/pull/51?

https://github.com/signadot/charts/actions/runs/5548751714/jobs/10132084961

**Comment by foxish** [comment]
Yeah, it tried to re-release v0.12.0 because it was merged separately. Should be fine - v0.13.0 should have those changes, so, we're good.

**Comment by scott-cotton** [comment]
> The build for this PR failed in the `Run chart-releaser` step. Is it ok to ignore that and proceed with merging #51?
> 
> https://github.com/signadot/charts/actions/runs/5548751714/jobs/10132084961

I think so -- that merge shouldn't have released anyway, so the failure is correct. (already exists)

**Pull request merged**
